---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hermes-model-secret
  namespace: hermes
spec:
  encryptedData:
    OPENCODE_GO_API_KEY: AgBk4x6SQp8Ex8a2RIKgX6JduC6ItnnQkMKRCewh+rAhSwnQnad0vtnb5MV8NIivyjrKtnbsKi1Gdo9XFrglQjQieneGvdFX4mvz3DsMZoT7uszcDUp8dArouMGDcnaIro7o0bPGmSlndxCgzgpRnxe6u5gQthAHvQrstXc16RRP71sPrRQS3gbyz6l7drD7iv2mNpX7588MT4AiQEICMIa+Vejp/iOOSrkFpjEylc6iokyH9w76NMFQhXVCTm4mhrH55W0lIzJYLR9oxIyJ4otnvEAk65IKL3x/j46qP8iOK4kdaIUUsixR2xPGKHmhMh9Z4Tz1mQf61t0LYcI/EMBPDqr1+HEe3esut2kLifN7yybCl1E5SwDfRUpayx5zqkbdjR3csNz03U+kGcuvO1vatk7lddgTFA7xMe7uiRgu349b4qrA/+dpNoLMR0warWTH4ZbEn4O44M1fcfqasdpYqVrxkZUfwUR+jseMCiijLhrFYPlouLgbm4Wcunr1Qoi4TiucPbtFUkrKD8vjg5TZspKJc/wJTCgN8+zlNTkYB02xpgNoCknOduFf4TN6bVq/gFhMKw2xp3QXFqOSV5Wyp+rd17+oPsXNUnOQVOCKzjjrKb3zsdN3HkDbeUuZcQm5U+dJko/+dBnCUNRoQfjGEkrHQScB62NBcxiyyoaTIzF5gPkxv/8ZkQ8h2fBbq0Ustgurt5AFpn84mvZlPswey1HU6ox2Jqg9JIWeHPp7obiykCVasVQVokxMhVbrmCygwE2TG53KgxDGNOwjkSAv2CoI
  template:
    metadata:
      name: hermes-model-secret
      namespace: hermes
