---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hermes-github-secret
  namespace: hermes
spec:
  encryptedData:
    GITHUB_TOKEN: AgCospTdVd52kEt/tkDwSR5EWZI6iqwEb0FRUviimhVHXpIoXMX6XwqWc7ndqjue6L1KaILfVVXXWHSILdtm1Dq2dXYu8bK0iWgBUl+JSMGfw668vmXE+TZoWnPl+M4KGXS9C2xATpg/iuJiv7ZnFiUuU6IJKUE82iRul3qoG5DJWE47saWqOTcaD7xUN35t1z9h7UDPLxQTBnxvufeptL1ORJQ3T1J+TwiwuxuQoMqSf4u85mTiWYSSmwzi1hg0nXJxwnhUpEzG/ayHVIS/A0+fvc4qa8m8qcxSXXwtTygkyzZnCz6W76yU0LVJNhkcqM03ilLTjo8oDa9hfZQxkLBh+tO6uekfjaPI7TlPR3yabOgql33mrTbMThjjwf89oUjTerNqoHNLacG9cMfzurBvbITjzpRYIqKWJC+JdTw09pPeOTk6/QZpt7ZUMn6tm/IsiORR1LAyQWLuHy6cc0W0dYaWwJcZ1touO/tq5MgAQ45Uca7ci06F+ze7l3TfVlW0r5oUIA2gj6YJMVnEv7UIX4vrIBmgjjE49/2zpTwpy7uSCIPNjQ+Pd7lx/3N644tjQcDAC0j/aigl4XPVl0UTMbfdW9O9eIJlDGGh+W5Re0joW4Ln4BDX8a3WoVhYi2VQlt9Ib5uSoReLfHQ6BUftI8nJ1RjdRaQajUeAuKBchgOvMQFgieFQSzSDPvvvegv/3ruaUmVIdPL1jDdkZRiX7+/K/PoNUsUfChBgNFMx+WP9wD79q5xf5OuRbv4RaEbcnSt2xH6CT6Vw5QHKlDIkaO4yxzH8HpWdXP9uWTdqdYjwk5pUtVP4M7FUETo=
  template:
    metadata:
      name: hermes-github-secret
      namespace: hermes
