---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hermes-api-server-secret
  namespace: hermes
spec:
  encryptedData:
    API_SERVER_KEY: AgCFvA0Jts14VqqSy0VCe7qPg/PSaSsSOoF1dbl+WjKZRFia4275XGZjqmQPdO0bzQa8n4cT4J7Qs4crjizVkvkZqhzydTNZAtj/zet7xXfwct8FDiOwVQAGr8Vm0yCnKM8vIvaY0gxkYxvOIb8HCDG6nIlyngKZ57N0V9WzppDydD5GmrVVkuFNIM02j6VbTybxxelRWdpNfphX0znGG/r8X2uHmzLN0WaxzVUl0pMfdpyJfhFkeDoHYqjlVlOfRoXJe8ueCbNtsf7MamUzVGD+iPyTtOzFJ+BKzw4i/0Xv4+KBNl8p54381FYVlMHuBfkZ4qzKwItDBUZFCwUKQYmE7j7Ihejy2iiCxEWg6qLsCQSYHQxrfoUS6rXoPFecI5FLNvmEF+qJ89Mxtev4+9OSnEo6au45IV766Awbv+/uvsKeDtzTgtq9eZFzB71EXYXUzXUTupUWPjHz2t8eZvlq6cHZGmL7HjiqZ1IUyN9mJchzA0mEHdpqTkjh7QXsGnqJi6pncC4A4hGPJxiWZnwNUZACz112UxJLsfNTEyRMMIRF92jtGnvDwQcklYy1Bs7SStgRtmNxwdKdvTgXFItaKBNkZAJbocQ685+GOMiRPxbpRPMoZ4UZjtESd3El1qoyzl/sfWq2c1xU+gWsA5Vq2o1PHoRQ5e4Uk5pA/p22WZq7DHHlkLhxfsWGIPBAAV9sYpSN1rfT8RPayZtnQLUNZ+Tj0jCu0GuwtNg7KF7HotbZ45oIZdz1bWlelLJ5xEKHVA6UCAUhLCRD/sSZ
  template:
    metadata:
      name: hermes-api-server-secret
      namespace: hermes
