---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hermes-model-secret
  namespace: hermes
spec:
  encryptedData:
    OPENCODE_GO_API_KEY: AgBxIyS0lJPTTnSwG7HD6rbZGgNv/UZBz50hheVLr5pzU0jXPu+nZQSdcoJmryOvADoSCZNTGVEt1Uj+V9Md2n2FjA5PaY8u0rcjJcqVmMAU3I0SHcRKcljd+QO6wQ6GZ0jx38EETLbw/oTynVmoDMf/yEmR7JjOfrV2m5+WvpWC8/e4vSKOyOToqHSKUxIP54CKx2j4uFNKIv+olxqAMMv9w28ont6HLShtdnEpatSsx/6BCeamRfpbmDjgHT/HcT9fnQiKY6UNSkpYuo2A5fQHJVDhvwHDDUZDl9OtlhWteeUIbZ0oKcjMf85GaM7u0C0MH+B8ZgHncja2SRiaYGNAo3e30mt2GkQfqxWZWyqAmZQAwk58gnA+aCw+FScAfxG50m/4awcvNFONZ8CX6oa/ikJqg9TV1M95c6jrHH1t+pxPY7amF+LHMNG3JAJqLT/Tja2rF/zSrD6MyD7jd85wCIsIphGaZAkiCcqhipPsFYbJMYVsC+l0cWrQc4ehv4p1TnuRrbEzNl90/+v0MqndknUgcfywmayLH+cAHmqDfJGnxogNMkoxC7WOdBMJ3Bu9R37v3g3nHXyxpjMYvG5xNiwHA+mDNY77itZzy2uQg8aHO3aXaYQ62+0fY+Q//IMhFvu8f9ndbP5mXiDVdK9n6Azlb++1PGOHyUFqabashoqKALxPAGcJd3KBqCrEqRb1N/MCh1KNCWm7uVmjgYAfYFZF5GyX9ZIEPnA6t1Xj+vXnL70CzugVFAjxX+mt736lD85mItQt/e8yElpNMQ0lV6jQ
  template:
    metadata:
      name: hermes-model-secret
      namespace: hermes
